version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 2244
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql

  spring-backend:
    build:
      context: ./Backend/Product
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/ecommerce
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=2244
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - backend

  frontend:
    container_name: frontend-container
    build:
      context: ./Frontend
    environment:
      - REACT_APP_BACKEND_URL=http://spring-backend:8080
    ports:
      - "80:80"
    depends_on:
      - spring-backend
    networks:
      - backend

networks:
  backend:
    external: false

volumes:
  mysql_data:
    driver: local
